### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'.

### ISSUE THREAD

**Issue by MartyLake** [doorstop-dev/doorstop#609] opened 2023-10-08 19:14 UTC
Hello,

Installing doorstop and launching in an empty directory yield this error:

```
$ doorstop
Traceback (most recent call last):
  File "/opt/homebrew/bin/doorstop", line 5, in <module>
    from doorstop.cli.main import main
  File "/opt/homebrew/lib/python3.11/site-packages/doorstop/__init__.py", line 8, in <module>
    from doorstop.core import (
  File "/opt/homebrew/lib/python3.11/site-packages/doorstop/core/exporter.py", line 10, in <module>
    import openpyxl
  File "/opt/homebrew/lib/python3.11/site-packages/openpyxl/__init__.py", line 4, in <module>
    from openpyxl.compat.numbers import NUMPY, PANDAS
  File "/opt/homebrew/lib/python3.11/site-packages/openpyxl/compat/__init__.py", line 5, in <module>
    from .strings import (
  File "/opt/homebrew/lib/python3.11/site-packages/openpyxl/compat/strings.py", line 10, in <module>
    from .numbers import NUMERIC_TYPES
  File "/opt/homebrew/lib/python3.11/site-packages/openpyxl/compat/numbers.py", line 49, in <module>
    numpy.float,
    ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
```

Maybe by updating openpyxl, the error will go.

EDIT: I deleted line 49 of "/opt/homebrew/lib/python3.11/site-packages/openpyxl/compat/numbers.py", and now it seems load.

**Comment by neerdoc** [comment] 2023-12-30 21:35
I cannot reproduce this, and even if I could, the problem is in the openpyxl library since it errors out on the import of the library.

Closing this.

**Closed by neerdoc** 2023-12-30 21:35 UTC
Labels: bug, help wanted
